config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: 'http://localhost:3000'
  devise_for :users

  resources :projects do
    resources :bugs, except: :index
  end

  resources :prouses do
    post '/add_developer', to: 'prouse#add_developer', as: 'add_developer'
    post '/add_qa', to: 'prouse#add_qa', as: 'add_qa'
    post '/remove_developer', to: 'prouse#remove_developer', as: 'remove_developer'
    post '/remove_qa', to: 'prouse#remove_qa', as: 'remove_qa'
  end

  post '/assign', to: 'bugs#assign', as: 'assign'
  post '/markcomplete', to: 'bugs#markcomplete', as: 'markcomplete'

  root to: 'projects#welcome'
end

app/views/shared/_assigndeveloperandqa.html.erb
<div class= "add_remove_dev_qa">

  <h1>Assign Developers and QA's to this Project</h1>  <br/>

  <div class= "add_remove_dev">
    <%= form_with url: prouse_add_developer_path(@project.id), class: 'dev_form', local: true do |f|%>
    <%= f.select(:developer_for_this_project, @all_developers-@project_developers , {}, {class: "form-control input-md select_fild"}) %>
    <%= f.hidden_field :project, :value => @project.id %>
    <%= f.submit "Add Developer To This Project", class: 'btn btn-success btn-md btn-block', id: 'dev_form'%>
    <% end %>
  </div>

  <div class= "add_remove_qa">
    <%= form_with url: prouse_add_qa_path(@project), class: 'qa_form', local: true do |f| %>
    <%= f.select(:qas_for_this_project, @all_qas-@project_qas , {}, { class: "form-control input-md select_fild"}) %>
    <%= f.hidden_field :project, :value => @project.id %>
    <%= f.submit "Add QA To This Project" , class: 'btn btn-success btn-md btn-block', id: 'qa_form'%>
    <% end %>
  </div>

</div>

app/views/shared/_bugform.html.erb
<div class="col">

      <h3 class="text-center"><%= formtitle %></h3>

      <%= form_with(model: [ project, bug ], local: true) do |form| %>

      <% if @bug.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@bug.errors.count, "error") %> prohibited
          this bug from being saved:
        </h2>
        <ul>
          <% @bug.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title , :class => 'form-control input-lg' %>
      </div>

      <div class="form-group">
        <%= form.label :description %><br>
        <%= form.text_area :description , class: 'form-control input-lg'%>
      </div>

      <div class="form-group">
        <%= form.label :deadline %><br>
        <%= form.date_select :deadline, { :start_year => Time.now.year }%>
      </div>

      <%= form.label :screenshot  %><br>
      <%= form.file_field :screenshot%>
      <br>
      <div class="form-group">
        <%= form.label :bugtype  %><br>
        <%= form.select :bugtype, Bug.bugtypes.keys , {}, { class: "form-control input-lg" }%>
      </div>

      <div class="pt-1 mb-4">
        <%= form.submit "#{buttontext}" , class: 'btn btn-info btn-lg btn-block'%>
      </div>
      <% end %> <br/>

      <%= link_to 'Back', project_path(project) %>

</div>

app/views/shared/_bugstablefordeveloper.html.erb
<table class="table table-bordered table-hover" >
    <thead>
     <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Screenshot</th>
      <th>Type</th>
      <th>Status</th>
      <th>View</th>
      <th>Mark it Complete</th>
    </tr>
  </thead>
  <tbody>
   <% @project.bugs.each do |bug| %>
   <%if (bug.dev_id==current_user.id) %>
   <tr>
    <td><%= bug.title %></td>
    <td><%= bug.description %></td>
    <td><%= bug.deadline %></td>
    <td><%= image_tag bug.screenshot, width:"50px" if bug.screenshot.attached? %></td>
    <td><%= bug.bugtype %></td>
    <td><%= bug.status %></td>
    <td><%= link_to 'View', project_bug_path(bug) %></td>
    <%if (current_user.user_type=='Developer') %>
    <td>
   <%if (bug.status=="completed" || bug.status=="resolved") %>
      <%= button_to 'Mark it Complete', {}, { :class => "btn btn-success btn-sm" , :disabled => true} %>

    <% else %>

    <%= form_with url: markcomplete_path(@bug), remote:true, local: true do |f| %>
      <%= f.hidden_field :pid, :value => @project.id %>
      <%= f.hidden_field :bid, :value => bug.id %>
      <%= f.submit "Mark it Complete" , { :class => "btn btn-success btn-sm"}%>
      <% end %>

    <% end %>
      </td>
      <% end %>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/shared/_bugtableformanagerandqa.html.erb
  <table class="table table-bordered table-hover" >
    <thead >
     <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Screenshot</th>
      <th>Type</th>
      <th>Status</th>
      <th>View</th>
      <%if (current_user.user_type=='QA' ) %>
      <th>Edit</th>
      <th>Delete</th>
      <% end%>
      <%if (current_user.user_type=='Developer' ) %>
      <th>Assign Bug to Yourself</th>
      <% end%>
    </tr>
  </thead>
  <tbody>
   <% @project.bugs.each do |bug| %>
   <%if (bug.dev_id!=current_user.id) %>
   <tr>
    <td><%= bug.title %></td>
    <td><%= bug.description %></td>
    <td><%= bug.deadline %></td>
    <td><%= image_tag bug.screenshot, width:"50px" if bug.screenshot.attached? %></td>
    <td><%= bug.bugtype %></td>
    <td><%= bug.status %></td>
    <td><%= link_to 'View', project_bug_path(bug) %></td>
    <%if ( current_user.user_type=='QA' && bug.user_id==current_user.id ) %>
    <td><%= link_to 'Edit', edit_project_bug_path(bug) %></td>
    <td><%= link_to 'Delete', [bug.project, bug],
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    <%if (current_user.user_type=='Developer') %>
    <td>
      <%if (bug.status=="completed" || bug.status=="resolved") %>
      <%= button_to 'Assign Bug To Yourself', {}, { :class => "btn btn-success btn-sm" , :disabled => true} %>

    <% else %>
      <%= form_with url: assign_path(@bug), remote:true, local: true do |f| %>

      <%= f.hidden_field :pid, :value => @project.id %>
      <%= f.hidden_field :bid, :value => bug.id %>
      <%= f.submit "Assign Bug To Yourself" , { :class => "btn btn-success btn-sm"}%>

      <% end %>
      <% end %>

    </td>

    <% end %>
  </tr>
  <% end %>
  <% end %>
</tbody>

</table>

app/views/shared/_currentuserprojects.html.erb
<table class="table table-bordered table-hover" >
    <thead class="thead-dark">
     <tr >
      <th>Title</th>
      <th>Description</th>
      <th>View</th>
      <%if ( current_user.user_type=='Manager') %>
      <th>Edit</th>
      <th>Delete</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
   <% current_user.projects.each do |project| %>
   <tr>
    <td><%= project.title %></td>
    <td><%= project.description%></td>
    <td><%= link_to 'View', project_path(project) %></td>
    <%if ( current_user.user_type=='Manager') %>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Delete', project_path(project),
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
  <% end %>
</tbody>
</table>

app/views/shared/_navigationbar.html.erb
<nav class="navbar navbar-light " style="background-color: #00203FFF; border-radius: 0;  padding: 20px 50px; box-shadow: rgba(0, 0, 0, 0.4) 0px 1px 20px">
  <span class="navbar-brand" style=" font-size:20px;color: white;">BUGZILLA</span>
<div style="float: right;display:inline-block;width:23%; ">
  <%= link_to "Edit Account", edit_user_registration_path ,
  {:style=>'color:white; font-size:15px; width:45%; margin-top: 5px; padding: 10px; color: white; display:inline-block;',
   :class => "btn btn-lg btn-success"}%>

  <%= link_to "Sign out", destroy_user_session_path ,
  {:method => :delete, :style=>'color:white; font-size:15px; width:45%; margin-top: 5px; padding: 10px; color: white; display:inline-block;',
   :class => "btn btn-lg btn-danger"}%>
</div>
</nav>

app/views/shared/_notSignedInNavbar.html.erb
  <nav class="navbar navbar-light " style="background-color: #00203FFF; border-radius: 0;  padding: 20px 50px; box-shadow: rgba(0, 0, 0, 0.4) 0px 1px 20px">
    <span class="navbar-brand" style=" font-size:20px;color: white;">BUGZILLA</span>
  </nav>

app/views/shared/_otherusersprojects.html.erb
<%if ( current_user.user_type!='Developer') %>

<div class="bugs_and_projects_table">
  <h1>Other Projects</h1>
  <br />

  <table class="table table-bordered table-hover" >
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <% if project.users.pluck(:id).include?(current_user.id)%>
      <p></p>

      <% else %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description%></td>
        <td><%= link_to 'View', project_path(project) %></td>
        <%if (current_user.id == project.users.pluck(:id))%>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project_path(project),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>

      <% end %>

      <% end %>
    </tbody>
  </table>

</div>

app/views/shared/_projectdetails.html.erb
<div class="jumbotron">
  <h1> <%= @project.title %> </h1>
  <p class="lead"> <%= @project.description %> </p>
  <hr class="my-4">
  <p>Manager : <%= @project.users.pluck(:username)[0] %></p>

  <p>Developers : </p>
  <% @project_developers.each do |developer| %>
  <p style="display: inline-block;"> ● <%= developer %></p>
  <% end %>
  <p>QAs :</p>
  <% @project_qas.each do |qa| %>
  <p style="display: inline-block;"> ● <%= qa %></p>
  <% end %>
  <br/>

  <%if (@project.users.pluck(:id).include?(current_user.id) && current_user.user_type=='Manager') %>
  <%= link_to 'Edit', edit_project_path(@project) , { :class => "btn btn-success btn-sm"}%>
  <% end %>

  <%= link_to 'Back', projects_path , { :class => "btn btn-primary btn-sm"}%>  <br/>  <br/>

  <div class="tags">
    <span class="label label-default">No. of Developers : <%= @project.users.select{ |element| element.user_type=="Developer"}.count() %></span>
    <span class="label label-default">No of QA's : <%= @project.users.select{ |element| element.user_type=="QA"}.count() %></span>
  </div>

</div>

app/views/shared/_removedeveloperandqa.html.erb
<div class= "add_remove_dev_qa">

  <h1>Remove Developers and QAs from this Project</h1>  <br/>

  <div class= "add_remove_dev">
    <%= form_with url: prouse_remove_developer_path(@project.id), remote:true, class: 'dev_form', local: true do |f| %>
    <%= f.select(:developer_for_this_project, @project_developers, {}, { class: "form-control input-md select_fild" }) %>
    <%= f.hidden_field :project, :value => @project.id %>
    <%= f.submit "Remove Developer From This Project" , class: 'btn btn-danger btn-md btn-block'%>
    <% end %>
  </div>

  <div class= "add_remove_qa">
    <%= form_with url: prouse_remove_qa_path(@project.id), remote:true, class: 'qa_form', local: true do |f| %>
    <%= f.select(:qas_for_this_project, @project_qas, {}, { class: "form-control input-md select_fild" }) %>
    <%= f.hidden_field :project, :value => @project.id %>
    <%= f.submit "Remove QA From This Project" , class: 'btn btn-danger btn-md btn-block'%>
    <% end %>
  </div>

</div>