config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: 'http://localhost:3000'
  devise_for :users

  resources :projects do
    resources :bugs, except: :index
  end

  resources :prouses do
    post '/add_developer', to: 'prouse#add_developer', as: 'add_developer'
    post '/add_qa', to: 'prouse#add_qa', as: 'add_qa'
    post '/remove_developer', to: 'prouse#remove_developer', as: 'remove_developer'
    post '/remove_qa', to: 'prouse#remove_qa', as: 'remove_qa'
  end

  post '/assign', to: 'bugs#assign', as: 'assign'
  post '/markcomplete', to: 'bugs#markcomplete', as: 'markcomplete'

  root to: 'projects#welcome'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, length: { minimum: 6 }

  has_many :prouse, dependent: :destroy
  has_many :bugs, dependent: :destroy
  has_many :users, through: :prouse, dependent: :destroy
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include Projectconcerns

  skip_before_action :authenticate_user!, only: [:welcome]

  before_action :find_current_user, only: %i[create destroy update]
  before_action :project_by_id, only: %i[show edit update]

  def welcome; end

  def index
    @projects = Project.all
  end

  def show
    developers_and_qas
  end

  def new
    @project = Project.new
    render 'new'
  end

  def edit; end

  def create
    create_new_project
    authorize @project
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: ' Project has been created successfully ' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html do
          flash[:alert] = 'Project was not created'
          render 'new'
        end
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: ' Project has been updated successfully ' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html do
          flash[:alert] = 'Project was not updated'
          render 'edit'
        end
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    find_destroy_project
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_path, notice: ' Project has been deleted successfully ' }
        format.json { head :no_content }
      else
        format.html { redirect_to project_path, notice: ' Project was not deleted ' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/views/projects/edit.html.erb
<%= render "shared/navigationbar" %>

<body style="background-color: #00203FFF;">
  <div class="new_edit_project">
    <section class="container mx-auto">
      <div class="row">
       <div class="col">
        <h3 class="text-center">Edit Project</h3>

        <%= form_with(model: @project, local: true) do |form| %>

        <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= form.label :title %><br>
          <%= form.text_field :title , :class => 'form-control input-lg'%>
        </div>

        <div class="form-group">

          <%= form.label :description %><br>
          <%= form.text_area :description , :class => 'form-control input-lg'%>
        </div>

        <div class="pt-1 mb-4">
          <%= form.submit "Edit this Project" , class: 'btn btn-info btn-lg btn-block'%>
        </div>
        <br/>
        <% end %>
        <%= link_to 'Back', projects_path %>
       </div>
      </div>
    </section>
  </div>
</body>

app/views/projects/index.html.erb
<%= render "shared/navigationbar" %>

<br />

<div class="bugs_and_projects_table">

  <h1>Your Projects</h1>
  <br />

  <%= render "shared/currentuserprojects" %>

<%if ( current_user.user_type=='Manager') %>
<%= link_to 'Create New Project', new_project_path , {:style=>'width:15%;', :class => "btn btn-success"}%>
<% end %>
<%= link_to 'Back', root_path , { :class => "btn btn-primary btn-md"}%>
</div>

<br />

<%= render "shared/otherusersprojects" %>

app/views/projects/new.html.erb
<%= render "shared/navigationbar" %>

<body style="background-color: #00203FFF;">
  <div class="new_edit_project">
    <section class="container mx-auto">
      <div class="row">
       <div class="col">
        <h3 class="text-center">Add New Project</h3>

        <%= form_with scope: :project, url: projects_path, local: true, validate: true do |form| %>

        <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="form-group">
          <%= form.label :title %><br>
          <%= form.text_field :title,  :class => 'form-control input-lg'%>
        </div>

        <div class="form-group">

          <%= form.label :description %><br>
          <%= form.text_area :description, :class => 'form-control input-lg'%>
        </div>

        <div class="pt-1 mb-4">
          <%= form.submit "Add this Project" , :class => 'btn btn-info btn-lg btn-block'%>
        </div>
        <br/>
        <% end %>

        <%= link_to 'Back', projects_path %>
       </div>
      </div>
    </section>
  </div>
</body>

app/views/projects/show.html.erb
<%= render "shared/navigationbar" %>

<%= render "shared/projectdetails" %> <br/>  <br/>

<%if (@project.users.pluck(:id).include?(current_user.id) && current_user.user_type=='Manager') %>

<%= render "shared/assigndeveloperandqa" %>  <br/>  <br/>

<%= render "shared/removedeveloperandqa" %>

<% end %>

<%if (current_user.user_type=='Developer') %>

<div class="bugs_and_projects_table">

  <h1>Your Assigned Bug & Features</h1>  <br />

  <%= render "shared/bugstablefordeveloper" %>

</div>

<% end %>

<div class="bugs_and_projects_table">
  <%if (current_user.user_type!='QA') %>
  <br />
  <br />
  <% end %>
  <h1>Bugs & Features</h1>
  <br />

<%= render "shared/bugtableformanagerandqa" %>

<%if (current_user.user_type=='QA') %>
<%= link_to 'Add New Bug', new_project_bug_path(@project) , {:style=>'width:15%;', :class => "btn btn-success"}%>
<% end %>
</div>

app/views/projects/welcome.html.erb
<div id="welcome_page">

  <% if user_signed_in? %>

  <%= render "shared/navigationbar" %>

  <div class="welcome_page_content">

    <h1 class="text-center text-uppercase">Welcome to Bugzilla</h1>  <br/>

    <h4 class="text-center">
      Bugzilla is a robust, featureful and mature defect-tracking system, or bug-tracking system. Defect-tracking systems allow teams of
      developers to keep track of outstanding bugs, problems, issues, enhancement and other change requests in their products effectively.
      Simple defect-tracking capabilities are often built into integrated source code management environments such as Github or other web-based
      or locally-installed equivalents. We find organizations turning to Bugzilla when they outgrow the capabilities of those systems -
      for example, because they want workflow management, or bug visibility control (security), or custom fields.  <br/>  <br/>
      <%= current_user.username %> you are signed in as  <%= current_user.roles.pluck(:name).first%>  </h4>  <br/>  <br/>  <br/>

      <div>
       <%= link_to "View your Projects", projects_path , {:style=>'width:30%;', :class => "btn btn-lg btn-success w-100"}%>
     </div>

   </div>

   <% else %>

   <%= render "shared/notSignedInNavbar" %>

   <div class="welcome_page_content notsigned">

     <h1 class="text-center text-uppercase ">Welcome to Bugzilla</h1>  <br/>

     <h4 class="text-center">
      Bugzilla is a robust, featureful and mature defect-tracking system, or bug-tracking system. Defect-tracking systems allow teams of
      developers to keep track of outstanding bugs, problems, issues, enhancement and other change requests in their products effectively.
      Simple defect-tracking capabilities are often built into integrated source code management environments such as Github or other web-based
      or locally-installed equivalents. We find organizations turning to Bugzilla when they outgrow the capabilities of those systems -
      for example, because they want workflow management, or bug visibility control (security), or custom fields.  <br/>  <br/>
      <span style="color: red;">You are not signed in.</span> Please </h4>  <br/>  <br/>  <br/>

      <div>
       <%= link_to "Sign In", new_user_session_path , {:style=>'width:20%;', :class => "btn btn-lg btn-success w-100"}%> or
       <%= link_to "Register", new_user_registration_path , {:style=>'width:20%;', :class => "btn btn-lg btn-primary w-100"}%>
     </div>

   </div>

   <% end %>

 </div>